package civica.nacional.Android.pageObjects;

public class RecargaTarjetaCivicaPage {
	
	public static final String MODULE_TU_TARJETA_CIVICA = "//android.widget.TextView[@text='Tu tarjeta Cívica']";
	public static final String PROGRESS_BAR = "//android.widget.ProgressBar";
	public static final String METRO_PROGRESS_BAR = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/iv_loading_metro']";
	public static final String BTN_SALDO_VISIBLE = "//android.widget.LinearLayout[@content-desc='Saldos']";
	public static final String RECHARGE_CIVICA_BTN = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_mifare_recharge']";
	public static final String DATOS_VISIBLE = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/txt_data_card']";
	public static final String DESPLEGABLE_TIPO_DOC = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/txt_type_document']";
	public static final String CONTINUE_BTN_DOC = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_continue']";
	public static final String ERROR_NO_POSIBLE = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/txt_message_password']";
	public static final String CC_BTN = "//XCUIElementTypeStaticText[@name='Cédula de ciudadania']";
	public static final String AL_PORTADOR_BTN = "//XCUIElementTypeStaticText[@name='Al portador (número de tarjeta cívica)']";
	public static final String CE_BTN = "//XCUIElementTypeStaticText[@name='Cédula de extranjera']";
	public static final String NUM_UNICO_BTN = "//XCUIElementTypeStaticText[@name='Número único de identificación personal']";
	public static final String PASAPORTE_BTN = "//XCUIElementTypeStaticText[@name='Pasaporte']";
	public static final String PERMISO_ESPECIAL_BTN = "//XCUIElementTypeStaticText[@name='Permiso especial de permanencia']";
	public static final String PERMISO_PROTECCION_BTN = "//XCUIElementTypeStaticText[@name='Permiso por protección temporal']";
	public static final String TI_BTN = "//XCUIElementTypeStaticText[@name='Tarjeta de identidad']";
	public static final String DOCUMENT_NUMBER_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/etIdNumber']";
	public static final String BTN_CONTINUAR = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_continue']";
	public static final String SALDO_INSUFICIENTE_TXT = "//android.widget.TextView[contains(@text, 'No tienes saldo suficiente')]";
	public static final String FIELD_FAV = "//XCUIElementTypeStaticText[@name='Favoritos']";
	public static final String VERIFICATED_DATA_VISIBLE = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/title_verify_data']";
	public static final String MONTO_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_add_amount']";
	public static final String METHOD_PAYMENT = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/check_method_civica']";
	public static final String CONTINUE_BTN = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_continue']";
	public static final String PASS_VISIBLE = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/title_set_password']";
	public static final String PASS_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/ed_validate_pin']";
	public static final String RECHARGED_CARD = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_validate_pin']";
	public static final String INCORRECT_PASS = "//android.widget.TextView[contains(@text, 'La clave no es correcta')]";
	public static final String SUCCESSFUL_RECHARGED = "//android.widget.TextView[contains(@text, 'Recarga realizada')]";
	public static final String END_BTN = "//android.widget.Button[contains(@text, 'Finalizar')]";
//	public static final String SKIP_BTN = "//XCUIElementTypeButton[@name='Omitir']"; No se usa en Android
	public static final String BACK_BTN = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/button_back_toolbar']";
	public static final String CONDICION_PARA_IF_VISIBLE = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_apply_for_card']";
	public static final String CONDICION_HORA_SERVICIO = "//*[contains(@text, 'No podemos recargar tu Tarjeta Cívica')]";
	public static final String CONDICION_SALDO = "//XCUIElementTypeCell/XCUIElementTypeOther";
	public static final String FECHA_HORA_TRANSACCION = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_mi_fare_date_approved_title']";
	public static final String NUM_AUTORIZACION = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_mi_fare_number_approved_title']/following-sibling::android.widget.TextView";
	public static final String BAD_PASS_IMPUT = "//XCUIElementTypeStaticText[contains(@name, 'La clave no es correcta')]";
	public static final String DATOS_TARJETA = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/title_data_card']";
	public static final String CUANTO_QUIERES_RECARGAR = "//android.widget.TextView[@text='¿Cuánto quieres recargar?']";
	public static final String METODO_PAGO = "//android.widget.TextView[@text='Método de pago']";
	public static final String SALDO_CLIENTE = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/textViewAmountBalance']";
	public static final String VALORES = "//androidx.recyclerview.widget.RecyclerView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/rv_amount_selector']";
	public static final String TXT_ICON_FAV = "//XCUIElementTypeStaticText[@name='Guarda tu favorito']";
	public static final String FIELD_NAME_ICON_FAV = "//XCUIElementTypeTextField[@name='Nombre, Máximo 15 caracteres.']";
	public static final String BTN_SAVE_FAV = "//XCUIElementTypeButton[@name='Guardar']";
	public static final String FAVS_INTO_RECHARGE_CARD = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_favorite_recharge']";
	public static final String GUARDA_FAVORITO_TXT = "//android.widget.TextView[contains(@text, 'Guarda')]";
	public static final String ELIMINA_FAVORITO_TXT = "//android.widget.TextView[contains(@text, 'Eliminar')]";
	public static final String ELIMINA_BTN = "//android.widget.Button[contains(@text, 'Eliminar')]";
	public static final String NOMBRE_PAGO = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tie_name_favorite']";
	public static final String SAVE_BTN = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_save_favorite']";
	public static final String CHANGE_NAME_TXT = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_title' and @text='Cambia el nombre de tu favorito.']";
	public static final String ACEPTAR_BTN = "//android.widget.Button[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_ok']";
	public static final String EDIT_INTO_RECHARGE_CARD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_add_amount']";
	public static final String FAV_NUMBER_ONE = "(//XCUIElementTypeOther)[39]";
	public static final String BTN_BACK_TO_RECARGAR_TARJETA_CIV = "(//XCUIElementTypeButton)[2]";
	public static final String FAV_LAYOUT = "(//android.widget.LinearLayout[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/layout_main'])[1]";
}
