package civica.nacional.Android.pageObjects;

public class RegistroCivicaPage {
	
	public static final String PROGRESS_BAR = "//android.widget.ProgressBar";
	public static final String HM_REGISTRATION_BTN = "(//android.widget.TextView[@text='Ingresa o regístrate'])[1]";
	public static final String DOCUMENT_TYPE_BTN = "//android.widget.ImageView[@content-desc='*']";
//	public static final String DROPDOWN_DOCUMENT_TYPE_CC = "//XCUIElementTypePickerWheel[@value='Cédula de ciudadanía']";
	public static final String DOCUMENTO_NUM_INPUT_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/etIdNumber']";
	public static final String CONTINUE_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String DATE_BIRTH_INPUT_FIELD = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/textinput_placeholder']";
	public static final String DATE_DAY = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[1]";
	public static final String DATE_MONTH = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[2]";
	public static final String DATE_YEAR = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[3]";
	public static final String OK_BTN = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_ok_date']";
	public static final String ERROR_FECHA = "//android.widget.TextView[contains(@text, 'Revisa la información')]";
	public static final String EDAD_MINIMA_PERMITIDA = "//android.widget.TextView[contains(@text, 'No cuentas con la edad mínima')]";
	public static final String BACKGROUND_VIEW_ON_BIRTH = "//XCUIElementTypeStaticText[@name='Fecha de nacimiento']";
	public static final String CONTINUE2_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String VALIDATE_REGISTER_TXT = "//android.widget.TextView[contains(@text, 'Regístrate')]";
	public static final String MANUAL_REGISTRATION_BTN = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tvManualRegister']";
	public static final String NAME_INPUT_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_name']";
	public static final String LASTNAME_INPUT_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_last_name']";
//	public static final String BACKGROUND_VIEW = "//*[@name='Vertical scroll bar, 3 pages']";
	public static final String CONTINUE3_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String VALIDATE_COMPLETE_INFO_TXT = "//*[@name='Complete la información']";
	public static final String DATE_ISSUED_FIELD = "//XCUIElementTypeScrollView/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField";
	public static final String DATE_ISSUED_EXP_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tiet_expedition_date']";
	public static final String DEPARTMENT_CITY_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_expedition_place_data']";
	public static final String DEPARTMENT_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_department_selected']";
	public static final String DEPARTMENT_FIELD_TO_SELECT = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_department_name']";
	public static final String CITY_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_city_selected']";
	public static final String CITY_FIELD_TO_SELECT = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/item_City']";
//	public static final String CONTINUE4_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String CELLPHONE_NUM_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_number_data']";
	public static final String MAIL_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_email_data']";
//	public static final String FIELD_VIEW = "//*[@name='Datos de contacto']";
	public static final String CONTINUE5_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String VALIDATE_EMAIL_CONFIRM_TXT = "(//*[@name='Confirma tu correo'])[2]";
	public static final String VERIFICATION_CODE_INPUT_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_otp']"; //Para el login funciona
	public static final String VERIFICATION_CODE_INPUT_FIELD_OTP = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_input_otp']";
	public static final String CONFIRMATION_CONTINUE_BTN = "//XCUIElementTypeButton[@name='Continuar']";
	public static final String VALIDATE_POPUP_CREATE_PASS_TXT = "//android.widget.TextView[@text='Vamos a crear tu clave']";
	public static final String CREATE_PASS_POPUP_BTN = "//android.widget.Button[@text='Crear clave']";
	public static final String CREATE_PASS_FIELD = "//android.widget.EditText[@text='Crea tu clave']";
	public static final String CONFIRM_PASS_FIELD = "//android.widget.EditText[@text='Confirma tu clave']";
	public static final String CONFIRM_POINT_VIEW = "//XCUIElementTypeStaticText[@name='Asigna una clave de 4 números.']";
	public static final String CREATE_PASS_BTN = "//android.widget.Button[@text='Crear clave']";
	public static final String CREATE_FINAL_PASS_BTN = "//android.widget.Button[@text='Crear clave']";
	public static final String VALIDATE_TERMS_TXT = "//android.widget.TextView[contains(@text, 'Términos y condiciones')]";
	public static final String ACCEPT_N1_FIELD = "(//android.widget.ImageView[@content-desc='*'])[2]";
	public static final String ACCEPT_N2_FIELD = "(//android.widget.ImageView[@content-desc='*'])[3]";
	public static final String ACCEPT_N3_FIELD = "(//android.widget.ImageView[@content-desc='*'])[4]";
	public static final String ACCEPT_N4_FIELD = "(//android.widget.ImageView[@content-desc='*'])[4]";
	public static final String CONTINUE_BNT_SINCE_TERMS = "//android.widget.Button[@text='Continuar']";
	public static final String CONFIRM_CEL_NUM_FIELD = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_phone_input']";
	public static final String CONTINUE_SINCE_CONFIRM_CEL_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String ACEPTAR_BTN = "//android.widget.Button[@text='ACEPTAR']";
	public static final String ACCEPT_POPUP_VERIF_CODE_CEL_BTN = "//XCUIElementTypeAlert/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[2]";
//	public static final String COD_VERIF_CEL_FIELD = "//*[@text='Ingresa el número de 6 dígitos']";
	public static final String ACCEPT_CODE_CEL_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String FALTA_POCO_POPUP = "//android.widget.TextView[contains(@text, 'Para continuar con tu registro')]";
	public static final String CONTINUAR_BTN = "//android.widget.Button[@text='CONTINUAR']";
	public static final String FINAL_POPUP_BTN = "//XCUIElementTypeAlert/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[2]";
	public static final String YEAR_FIELD_TO_SCROLL = "//*[@value='2023']";
	public static final String DAY_FIELD_TO_SCROLL = "//XCUIElementTypePickerWheel[@value=\"1\"]";
	public static final String MONTH_FIELD_TO_SCROLL = "//XCUIElementTypePickerWheel[@value='Enero']";
	public static final String INPUT_MAIL = "//*[@id=\"identifierId\"]";
	public static final String CONTINUE_BTN_LOGIN = "//*[@id=\\\"identifierNext\\\"]/div/button/span";
	public static final String INPUT_PASS = "//*[@id=\"password\"]/div[1]/div/div[1]/input";
	public static final String CONTINUE_BTN_PASS = "//*[@id=\"passwordNext\"]/div/button/div[3]";
	public static final String EXIT_MAIL_BTN = "//*[@id=\"passwordNext\"]/div/button/div[3]";
	public static final String WELCOME_CONTINUE_BTN = "(//XCUIElementTypeButton[@name='Continuar'])[2]";
	public static final String BTN_ACEPTAR_CEL = "//XCUIElementTypeButton[@name='Aceptar']";

}
