package civica.nacional.Android.pageObjects;

public class TransporteCivicaPageObjects {
	
//	public static final String TXT_PERMISOS_CIVICA = "//XCUIElementTypeStaticText[@name='¿Permitir a Cívica utilizar tu ubicación?']";
//	public static final String PERMITIR_AL_USAR = "//XCUIElementTypeButton[@name='Permitir al usar la app']";
//	public static final String BTN_PERMITIR_SIEMPRE = "(//XCUIElementTypeOther[@name='Barra de desplazamiento horizontal, 1 página'])[2]";
	public static final String MENU_HAMBURGUESA = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_menu_burger']";
	public static final String USER_BTN_HM = "//android.widget.LinearLayout[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/menu_private_profile']";
	public static final String BENEFICIOS_BTN = "//android.widget.LinearLayout[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/menu_private_travel_benefits']";
	public static final String PROGRESS_BAR = "//android.widget.ProgressBar";
	public static final String BENEFICIOS_MODULE_TXT = "//android.widget.TextView[contains(@text, 'Consulta tus beneficios de viaje en Civica')]";
	public static final String TXT_WITHOUT_BENEFITS = "//android.widget.TextView[contains(@text, 'Aún no tienes beneficios activos')]";
	public static final String SELECT_UBIC_LY = "//android.view.ViewGroup[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/ly_select_button']";
	public static final String DESPLEGUE_TRAYECTOS_GUARD = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_sheet']";
	public static final String DESPLEGUE_TRAYECTOS_SUGER = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btn_sheet']";
	public static final String TRAYECTOS_SUGER = "//android.widget.LinearLayout[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/ll_bottom_sheet_paint_route']";
	public static final String BTN_RETURN_SINCE_BENEFICIOS_VIAJE = "//android.widget.ImageView[@content-desc='*']";
	public static final String BTN_RETURN_A_DONDE_VAS = "(//android.widget.ImageView[@content-desc='*'])[1]";
	public static final String SALDOS_HOME = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/txt_balance']";
	public static final String MODULE_TRAYECTOS_SAVES = "//*[contains(@name, 'Trayectos guardados')]";
	public static final String TRAYECTO_PRESENT = "(//android.widget.TextView[contains(@text, 'min')])[3]";
//	public static final String EMPIEZA_A_VIAJAR = "//*[contains(@text,'¡Empieza a viajar!')]";
	public static final String ALL_JOURNEYS = "//android.widget.Button[@text='Ver Todos']";
	public static final String TXT_ALL_JOURNEYS_MODULE = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/toolbar_tittle' and contains(@text, 'Trayectos guardados')]";
	public static final String TXT_TRIP_PROGRESS = "//*[contains(@text, 'Viaje en curso')]";
	public static final String BTN_RETURN_SINCE_TRAYECTOS_GUARDADOS = "//android.widget.ImageView[@content-desc='*']";
	public static final String MODULE_NEAR_PLACES = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/txt_title_nearby_Places']";
	public static final String LC_COMERCIO = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/text_nearby_place' and @text='Comercio']";
	public static final String LC_FINANCIERO = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/text_nearby_place' and @text='Financiero']";
	public static final String TRAVEL_WITH_QR = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/btnGoToTravelQr']";
	public static final String HOME_W_ARE_U_GOING = "//android.widget.TextView[@text='¿A dónde vas? Planifica tu viaje']";
	public static final String EMPIEZA_A_VIAJAR = "//android.widget.TextView[contains(@text, 'Empieza')]/parent::android.widget.LinearLayout/parent::android.widget.LinearLayout";
	public static final String MINS_JOURNEY = "(//android.widget.TextView[contains(@text, 'min')])[3]";
	public static final String FIELD_W_ARE_U_GOING = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_origin']";
//	public static final String FIELD_A_DONDE_VAS = "//XCUIElementTypeTextField[@name='¿A dónde vas?']";
	public static final String FIELD_INTO_W_ARE_U_GOING = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_origin']";
	public static final String JOURNAYS_SAVES_INTO_W_ARE_U_GOING = "//android.widget.TextView[@text='Trayectos guardados']";
	public static final String SEE_ALL_SINCE_W_ARE_U_GOING = "//android.widget.Button[@text='Ver Todos']";
	public static final String BTN_RETURN_SINCE_SEE_ALL_SINCE_W_ARE_U_GOING = "//android.widget.ImageView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/button_back_toolbar']";
//	public static final String MAP_FROMLOCATION = "//XCUIElementTypeImage[@name='ic_map_fromlocation']";
//	public static final String MAP_REAL_LOCATION = "(//XCUIElementTypeOther)[30]";
//	public static final String GPS_UBICATION = "//XCUIElementTypeButton[@name='ic ubicacion']";
//	public static final String BTN_SELECT_LOCATION = "//XCUIElementTypeButton[@name='Seleccionar ubicación']";
//	public static final String BTN_SHOW_JOURNEYS = "(//XCUIElementTypeOther)[42]";
//	public static final String BTN_HIDDE_JOURNEYS = "(//XCUIElementTypeOther)[40]";
	public static final String START_JOURNERY = "//android.widget.Button[contains(@text, 'Empezar trayecto')]";
	public static final String CURRENT_LOCATION = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_origin']";
	public static final String ADONDEVAS_LOCATION = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/et_destination']";
	public static final String SELECT_DEPARTURE_TIME = "//android.view.ViewGroup[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/ly_select_date']/android.widget.ImageView[2]";
	public static final String TIET_DATE = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tiet_date']";
	public static final String TIET_TIME = "//android.widget.EditText[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tiet_time']";
	public static final String DATE_DAY = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[1]";
	public static final String DATE_MONTH = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[2]";
	public static final String DATE_YEAR = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[3]";
	public static final String OK_BTN = "//android.widget.TextView[@resource-id='co.gov.metromedellin.appCivicanew.lab:id/tv_ok_date']";
	public static final String TIME_HOUR = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[1]";
	public static final String TIME_MINUTE = "(//android.widget.EditText[@resource-id='android:id/numberpicker_input'])[2]";
	public static final String ACEPTAR_BTN = "//android.widget.Button[contains(@text, 'ACEPTAR')]";
	public static final String CONTINUAR_BTN = "//android.widget.Button[@text='Continuar']";
	public static final String BTN_SELECT_ON_THE_MAP = "//android.widget.TextView[contains(@text, 'Elegir en el mapa')]";
//	public static final String FIELD_INPUT_DATE = "(//XCUIElementTypeButton)[6]";
//	public static final String FIELD_INPUT_DATE_HOUR = "//XCUIElementTypeApplication[@name='Cívica']/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]";
//	public static final String DATE_BIRTH_INPUT_FIELD = "//XCUIElementTypeStaticText[contains(@name,'Fecha de salida DD/MM/AAAA')]";
//	public static final String DAY_FIELD_TO_SCROLL = "(//XCUIElementTypePickerWheel)[1]";
//	public static final String MONTH_FIELD_TO_SCROLL = "(//XCUIElementTypePickerWheel)[2]";
//	public static final String YEAR_FIELD_TO_SCROLL = "//XCUIElementTypePickerWheel[@value='2024']";
//	public static final String FIELD_DEPERTURE = "//XCUIElementTypeStaticText[@name='Hora de salida']";
//	public static final String FIELD_HOUR = "(//XCUIElementTypePickerWheel)[1]";
//	public static final String FIELD_MINUTE = "(//XCUIElementTypePickerWheel)[2]";
//	public static final String FIELD_JORNADA = "(//XCUIElementTypePickerWheel)[3]";
//	public static final String BTN_ACEPTAR_HORA = "//XCUIElementTypeButton[@name='Aceptar']";
	public static final String BTN_BACK_FROM_MORE_SERVICES = "//android.widget.ImageView[@content-desc='*']";
//	public static final String BTN_REGRESO_MAS_SERVICIOS = "//XCUIElementTypeButton[contains(@name, 'Explorar')]";
//	public static final String SUGGESTED_ROUTES = "//XCUIElementTypeStaticText[@name='Trayectos sugeridos']";
//	public static final String BTN_BACK_FROM_SUGGESTED_ROUTES = "//XCUIElementTypeButton[contains(@name, 'Explorar')]";
//	public static final String CAMPO_INGRESA_DIRECCION = "//XCUIElementTypeTextField[contains(@name, 'Ingresa dirección')]";
}